### ISSUE TITLE
Add support for experiments and cohort selection

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#1]
It should be possible to configure experiments and cohorts on the main page. Only one experiment can be chosen at a time. One or many cohorts can be chosen at a time. By default all cohorts will be selected. The list of possible cohorts that the user will be able to choose from will depend on the experiment that is chosen.

Experiments are essentially datasets. Each experiment has one or more metrics associated with it. Cohorts are essentially populations. For each cohort, another line will appear in the chart and another item will appear in the legend.

These options could be presented in the existing Configuration box or as separate widgets: for example, Experiment could be a simple drop-down and Cohorts could be a multi-select box.

**Comment by rafrombrc** [comment]
We definitely don't want the experiment selection widget to be within the existing config box. That should be a widget that is visible on the main page at all times.

**Comment by rafrombrc** [comment]
The cohorts (i.e. populations) can remain inside the config box, for now though.

**Comment by rafrombrc** [comment]
This has now grown into a meta-bug, completion of this is blocked by #20, #28, #29, #30, #31, #32
