### ISSUE TITLE
Switch to using regular line graphs

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#102]
The 'stepwise' line graphs that we're using are great for CDF graphs but aren't as clear with the more PDF-like graphs we're using for experiments.

**Comment by gregglind** [comment]
(if you do this, I wonder if this possible to put the config for this up in the Window object, or in general, have more stuff 'exposed' to the window for messing about.  Not a real ask at all.  I am trusting that if you say it looks better, it looks better)

**Comment by rafrombrc** [comment]
It's less about looks than about clarity. Right now the graphs are hard to interpret because they jump from the prior value to the current value at a single point on the x-axis. It would be much more clear if the lines spanned the vertical distance during the interval and passed through the single value that we care about, instead of spanning the entire vertical distance in one place.

**Comment by spasovski** [comment]
https://github.com/mozilla/experiments-viewer/commit/50c091e
