### ISSUE TITLE
Legend should be smooshed left.

### ISSUE THREAD

**Issue by gregglind** [mozilla/experiments-viewer#112]
This css line:  `.legend` should be `justify-content: inherit` or such, NOT: `space-between`.   While you are in there, give those thingies a label and data attributes maybe :)

GL

**Comment by openjck** [comment]
Can you say more about what you mean by label and data attributes?

**Comment by gregglind** [comment]
Maybe add a literal className or a "data=" attribute.  It actually doesn't
matter at all and I found selectors to affect it just fine.

**Comment by openjck** [comment]
Sure thing. There was a data- attribute on the `<svg>`. I moved it up to the `<li>` so that it encompasses the name also.
