### ISSUE TITLE
Subtle loading bar idea

### ISSUE THREAD

**Issue by robhudson** [mozilla/experiments-viewer#118]
Imagine the loading bar is just a few pixel high bar across the top. This would be a nice indicator that charts are loading and when they are completed. It could also be a pie chart that fills in or whatever might work on the front-end.

Once we load the /datasets/ API we know the number of metrics (charts) for a given dataset and could use that to create a loading bar for the page. With each /metric/<id>/ API that loads we can push the loading bar one more tick.

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.
