### ISSUE TITLE
Show units in the hover description at the bottom of the page

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#150]
This is what the hover description looks like now:

<img width="294" alt="screen shot 2017-06-29 at 10 05 15 am" src="https://user-images.githubusercontent.com/933396/27700674-25d03bda-5cb3-11e7-8dad-a596848301af.png">

We should add units to these values. They may only be unit-less right now because they are generated using the default format string, and the default format string doesn't know the units of the charts that it's being used for. If that's the case, we'll either need to do a better job of customizing the format string for each chart or naming the units in the JSON that is made available to the front-end.

**Comment by rafrombrc** [comment]
This is blocked until there are units for each measurement available via the API.

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.
