### ISSUE TITLE
Show the y-value in the hover description at the bottom of the page

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#151]
This is what the hover description looks like now:

<img width="294" alt="screen shot 2017-06-29 at 10 05 15 am" src="https://user-images.githubusercontent.com/933396/27700739-6408e924-5cb3-11e7-9331-5ca0a051a274.png">

We should add the y-value of the data point to that hover description. Not the percent, but the actual y-value of that data point. For example, **351 users**. I think we already have the ability to do this, but we're not doing it in the default format string.

**Comment by openjck** [comment]
Actually, I don't think we have raw y values available to us, just percentages. Does that sound right, @robhudson?

**Comment by robhudson** [comment]
I think if you take the `numObs` * `p` you would get the raw value.

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.
