### ISSUE TITLE
Explore making Experiments Viewer public

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#153]
This was brought up during a meeting in San Francisco. Can we remove the login requirement and make Experiments Viewer public?

**Comment by openjck** [comment]
@rafrombrc I was wondering if you had any thoughts on this. Are stakeholders fine with making this data public or do they definitely want to keep things private? We'll make it work whatever their preference is, of course, but if they are fine with data being pubic that would definitely make many things easier.

**Comment by rafrombrc** [comment]
While this might be something we explore down the road, for now there are no plans to make this public. Even if some of the data is public, it's possible that there will be certain experiments that will always need to be kept private. We want to proceed for now with the current security model.

**Comment by openjck** [comment]
Great, sounds good. Thanks for the info!

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.

It sounds like making Test Tube data public is pretty unlikely, so I'm not going to bother opening an issue against Test Tube about that. But if I'm wrong just let me know and I'd be happy to.
