### ISSUE TITLE
Show a data timestamp

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#154]
Somewhere on the page, show a data timestamp. Make the timestamp as precise as possible: if the data is updated every hour, show the date and the hour. We had this on Distribution Viewer so it shouldn't be too hard to bring it back.

**Comment by robhudson** [comment]
Which date would we should? The import date/time? Or the aggregation date/time (which is usually 1 day behind)?

**Comment by openjck** [comment]
That's a good question. I want to say they would prefer the latter. What do you think, @rafrombrc?

**Comment by rafrombrc** [comment]
Yes, they want to see when the data itself is from, so we want the aggregation date/time.

**Comment by openjck** [comment]
@robhudson  We don't have that from the API yet, do we?

**Comment by robhudson** [comment]
@openjck Not yet. It is upstream but I'm not storing it yet. I'll need to record it with the dataset and then update the API to pass it up.
