### ISSUE TITLE
Show units for the x-axis

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#156]
The x-axis doesn't have any units right now. We should change that.

**Comment by openjck** [comment]
@robhudson Is it possible for the back-end to provide this in the API? This issue and #150 might be blocked until we have that.

**Comment by robhudson** [comment]
We don't have this data yet. It needs to come from upstream and upstream doesn't have it either. There's talk of a data dictionary service or adding more metadata to histograms.json.

**Comment by robhudson** [comment]
The backend is now sending units from the /metrics/ api. They may not be populated in the database but if so they will be an empty string. If metrics are available we can display them.

Changing owner to front-end.
