### ISSUE TITLE
Show me user counts for my experiment(s) and control

### ISSUE THREAD

**Issue by johngruen** [mozilla/experiments-viewer#167]
So that i can reason about how many users are in my experimental and control branches I would like to see user counts reflected in my dashboard's UI.

~~~So that I can reason about how fresh the data is in on my dashboard, i would like to see a a last updated time stamp.~~~

**Comment by johngruen** [comment]
Ah, looks like the second half of this is a dupe of #154

**Comment by johngruen** [comment]
![screenshot-2017-7-5 firefox experiments viewer](https://user-images.githubusercontent.com/3323249/27872511-045615b0-6177-11e7-9ccb-68dbf2f5f8c2.png)

**Comment by openjck** [comment]
Thanks, @johngruen. Does #155 cover the first part? Either way we appreciate the extra detail from you. I did open some issues from our meeting last week so there might be others you're interested in [within the list](https://github.com/mozilla/experiments-viewer/issues).

**Comment by johngruen** [comment]
Oh yeah, totally does!
