### ISSUE TITLE
Allow Different Plot Types for Different Metric Types

### ISSUE THREAD

**Issue by fbertsch** [mozilla/experiments-viewer#168]
**Immediate Need**: We need to be able to show crashes as a bar chart, with one bar per branch, and the height being the crash count per client.

**Longer-Term Need**: We need to separate out different types of charts for different types of data. Booleans should be displayed differently, counts are essentially just a single number. 

These may need to be toggled for different Metric Types: For example, counts used to be represented using Count Histograms. Now they are represented with Numeric Scalars. So some numeric scalars need to be represented as they currently are (PDF of counts), while numeric scalars that are counts should really just be displayed as a normalized count (same as crash bar chart).

There is probably more planning that needs to go in to this implementation, but it's worth thinking about as we move forward with the crashes plot. For example, instead of having multiple charts per metric, we instead make multiple rows for that same metric, just with the different plot types we'd like to enable. Sunah wants to see box-and-whiskers plots, given the confidence interval. Ideally we'd have a toggle to show specific types of plots.

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.

We have bar chart support in Test Tube. We use bar charts by default when there are less than 20 data points? Is there anything else you'd like to see different on Test Tube, Frank?
