### ISSUE TITLE
Need list of OSes to facet on

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/experiments-viewer#17]
We need a list (preferably less than like, 10) of OSes/versions to facet on

**Comment by sunahsuh** [comment]
@glind I can't seem to assign this to you (probably bc i don't have enough privileges on this repo)

**Comment by robhudson** [comment]
@sunahsuh I think you want @gregglind ?

**Comment by gregglind** [comment]
my bid:

windows 7, windows 10, windows_other, OSX, linux, other.

**Comment by bsmedberg** [comment]
For the OS, we want the Windows/Mac/Linux/other facets
and then on Windows we want OS version facets: win7, win8, win8.1, win10

@sunahsuh can you extrapolate details from there or do you need more specifics?

**Comment by sunahsuh** [comment]
Per a discussion with @gregglind yesterday, we're planning to do one level of faceting for the first round, but we can make these specific windows versions facets as well as "all windows"
