### ISSUE TITLE
?next query parameter is ignored after logging in

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/experiments-viewer#170]
If you directly load a particular experiment (e.g. https://moz-experiments-viewer.herokuapp.com/?ds=39&metrics=ALL&next=%2F%3Fds%3D52%26metrics%3DALL%26next%3D%252F%26pop%3DALL%26scale%3Dlinear%26showOutliers%3Dfalse&pop=ALL&scale=linear&showOutliers=false) the experiment dropdown automatically selects the first option in the list instead of the current experiment and if you did want to switch to the first option, the apply button is disabled.

**Comment by openjck** [comment]
It looks like the `?next` query parameter is being ignored.

### Steps to reproduce

1. Log out of the [staging site](https://moz-experiments-viewer.herokuapp.com/)
2. Follow a link to experiment 23 (like [this one](https://moz-experiments-viewer.herokuapp.com/?ds=23&metrics=ALL&pop=ALL&scale=linear&showOutliers=false))
3. Log in

### Actual result

Experiment 39 (the current default) is loaded

### Expected result

Experiment 23 is loaded
