### ISSUE TITLE
Create D3 display for bar charts

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#175]

**Comment by openjck** [comment]
Haven't started on this one yet. Not super excited since I suck at D3, but I'll take a look this week.

**Comment by spasovski** [comment]
I can obviously take a look soon but I'd argue this is a great way to get your feet wet into D3. There are both SVG and pure DOM solutions available.

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it. Test Tube does support bar charts.
