### ISSUE TITLE
Enh / debatable:  "something seems wrong" button

### ISSUE THREAD

**Issue by gregglind** [mozilla/experiments-viewer#182]
I realize that we have touched on this before with the "last run date", and the "github button".  Maybe a better answer is to have a 'something seems wrong' link, that describes how to troubleshoot / links to an email or whatever it is we WANT to do for the "no data" problem.

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.

Gregg, feel free to re-open this issue against Test Tube.
