### ISSUE TITLE
Add a button for getting the JSON that was used to build a chart

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#19]
This corresponds to mozilla/distribution-viewer#227:

@gregglind said it would be great to have a button next to each chart that links to the JSON that was used to build the chart. Exposing the raw data would help users re-purpose it.

**Comment by gregglind** [comment]
Button is okay.  JSON api is better.  Even a single button that gets all data in the page is better than nothing.  No supper great ideas about this, btw.

**Comment by openjck** [comment]
I was thinking we would have one button per chart. We do have a [JSON API](https://github.com/mozilla/experiments-viewer/blob/master/docs/api.md) already, if that's what you mean.
