### ISSUE TITLE
Pull  experiment metadata from Normandy

### ISSUE THREAD

**Issue by robhudson** [mozilla/experiments-viewer#191]
Normandy has information in their API that would allow us to display our data in a nicer way or add supplemental information about experiments within the experiment viewer.

URL: https://normandy.services.mozilla.com/api/v1/recipe/?latest_revision__action=3

During import we can fetch the latest data and update our records.

Questions:
- What fields should we gather and store within EV?
- Which fields make sense to collect and store within EV vs. fetching on the fly?
- How would we display this data in the front-end?

**Comment by rafrombrc** [comment]
Let's start with just the human readable name and any description that was included, although if you look at what's available and think there's something else we should pull down I'll trust your judgment.

My thought is that we should maybe be doing this during the import. Maybe let's start by pulling down data for any new experiments that we get. At some point in the future we may need to handle updating exp metadata in case it changed in Normandy, but I'm thinking maybe we punt on that for now.

As for the front end, let's consider this ticket to be for a) fetching the data from Normandy and b) making it available in the API. We can open new issues to deal with the front end changes needed to display the information (see #231).
