### ISSUE TITLE
TypeError: r is undefined

### ISSUE THREAD

**Issue by robhudson** [mozilla/experiments-viewer#209]
STR:

1. Load EV
2. Choose a different experiment. I chose `pref-flip-quantum-css-style-r1-1381147`
3. Charts don't load. Viewing the console I see: `TypeError: r is undefined`

**Comment by openjck** [comment]
This is a tricky one to pin down, especially because I can't reproduce it locally. Are you sure the charts don't load? They do for me.

**Comment by robhudson** [comment]
I only see it with that one experiment, not the others, which is odd. Perhaps there's some difference in the data with that one?

**Comment by rafrombrc** [comment]
Notes:
* Hitting 'refresh' causes the charts to start working for me
* This experiment doesn't have a 'control' group, seems likely to be related
