### ISSUE TITLE
Use date of partition as the date to display to users instead of import date

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/experiments-viewer#222]
Somewhat relatedly to the backfill issue, we should use the partition date (which is the last submission_date_s3 included in the data) instead of the time of import as the date that we show users to determine staleness of data -- it's misleading to show the import time when the data might be stale

**Comment by rafrombrc** [comment]
We'll want to make sure the UI clearly expresses what the date means.

**Comment by openjck** [comment]
@robhudson: This isn't provided from the back-end yet, is it?

**Comment by rafrombrc** [comment]
Date coming down from the API now reflects the most recent data in the data set, we just need to change the UI so users know this. Not sure what to use.... s/Imported on/Through/ maybe?
