### ISSUE TITLE
Implement Mann-Whitney-U for histograms

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#224]
This is a not urgent job that would be great for deepening Rob H's analysis / stats skills. First implementation in Python (landing in moz-telemetry-python) then reimplement in Scala (landing in moz-telemetry).

**Comment by robhudson** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1395571

**Comment by rafrombrc** [comment]
Closing bc there isn't any exp viewer work to be done for this issue.
