### ISSUE TITLE
Set up notification when data doesn't update

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#226]
It took 3 days from the time when Exp Viewer's data wasn't being updated for someone to notice and notify us. Ideally we'd have automatic monitoring and get notifications when the import isn't happening as expected.

**Comment by sunahsuh** [comment]
We knew (myself and frank) because of airflow alert emails -- if you'd like to expand the email alert list to include data tools we can definitely do that, but that won't really help with things like main_summary failures

**Comment by robhudson** [comment]
I'll send a PR to add myself to the upstream jobs so I'll know when those fail, which would mean the import job isn't run which means no data.

**Comment by robhudson** [comment]
https://github.com/mozilla/telemetry-airflow/pull/164

**Comment by robhudson** [comment]
Merged. Closing.
