### ISSUE TITLE
Show human friendly exp names

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#231]
Human readable experiment names will soon be available via the API. The display at the top of the page (and the page title, when it's updated to show the experiment) should be changed to show this instead of the non-friendly ID that's currently displayed.

**Comment by openjck** [comment]
Blocked by #191

**Comment by openjck** [comment]
We'll want to fall back to "machine names" (the type of names that are being used now) if a human-readable name is not available.
