### ISSUE TITLE
Backfill metadata for metrics that came down w/o any

### ISSUE THREAD

**Issue by robhudson** [mozilla/experiments-viewer#24]
The experiments viewer will end up with many more metrics than the distribution viewer, most of which we don't have in our database.

On encountering new metrics the plan is to add them to our list of metrics in the database, so they will then have an `id` and a `source_name`. The fields for `name`, `description`, `tooltip`, and `type` would remain empty and should/could be populated in some other way at a future date. Without these fields the front-end can simply display the `source_name` as the `name` and default to a basic tooltip showing the values.

This bug is to figure out if there is a better upstream source for this metadata about the metrics. Or if we want to create one that various tools pull from. Or other thoughts that come up we can discuss here.

**Comment by robhudson** [comment]
cc @gregglind

**Comment by gregglind** [comment]
https://hg.mozilla.org/mozilla-central/raw-file/tip/toolkit/components/telemetry/Histograms.json  for prior art (partial)

**Comment by rafrombrc** [comment]
First step is having the import script use the metric name as the title and description when better metadata isn't yet available, this is already handled in #25. We still need to figure out how to fetch and back-fill the full metadata afterwards.

**Comment by rafrombrc** [comment]
We're initially going to manage metric metadata by hand using the django admin UI, closing this.
