### ISSUE TITLE
Show 'b' value along x-axis

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#241]
Right now some of the x axes are showing the 'refRank' values as their labels and some are showing the 'b' values (although why this is so is a mystery to me... seems like https://github.com/mozilla/experiments-viewer/blob/master/viewer/static/js/app/components/containers/chart-container.js#L156 implies it should always be using 'refRank').

Anyway, going forward we want all of the graphs to be using the 'b' value for the labels. We want to take care, however, that for measurements of type 'exponential histogram' that the scaling of the axis is exponential (or at least that every distinct value is given the same amount of real estate) and not linear.

**Comment by robhudson** [comment]
Completed in 4c1ebbe192a0e787fe8a35470afc2a65ea4daba8
