### ISSUE TITLE
Set up Heroku staging pipeline

### ISSUE THREAD

**Issue by robhudson** [mozilla/experiments-viewer#26]

**Comment by robhudson** [comment]
We will keep the current Heroku instance as our "production" environment and set up a staging environment that will be deployed to continuously, and manually push to production.

**Comment by robhudson** [comment]
https://moz-experiments-viewer-staging.herokuapp.com/ is the staging app URL. This will be auto deployed from master when the CI tests pass.

To deploy to production is a manual button press from Heroku's pipeline interface. Or via the CLI using `heroku pipelines:promote -a moz-experiments-viewer-staging`.

**Comment by openjck** [comment]
👍
