### ISSUE TITLE
String scalars showing up as numeric

### ISSUE THREAD

**Issue by fbertsch** [mozilla/experiments-viewer#293]
See the [definition for a11y instantiators](https://dxr.mozilla.org/mozilla-central/rev/tip/toolkit/components/telemetry/Scalars.yaml#13), which is showing up as numeric in the viewer.

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.

Has this issue been addressed anyway? I see #292 was merged.
