### ISSUE TITLE
verify UintScalar vs ScalarBinary

### ISSUE THREAD

**Issue by spasovski** [mozilla/experiments-viewer#298]
Something is odd either with the data, its type, or simply the way we render it in the UI. 

The JSON is here: https://moz-experiments-viewer-staging.herokuapp.com/metric/314/?ds=tracking-protection-release-1397418&pop=control,treatment

and the chart is found at https://moz-experiments-viewer-staging.herokuapp.com/?ds=tracking-protection-release-1397418&metrics=ALL&pop=control%2Ctreatment&scale=linear&showOutliers=false

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.

Sunah and Davor, let me know if this an issue that also affects Test Tube.
