### ISSUE TITLE
Some cohort lines aren't visible

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#30]
On staging right now, group B in experiment 2 looks like it should be showing up in the graphs, but it doesn't. It might be that the lines aren't rendering, but it also might be that cohort got assigned the color black and it's just invisible against the black background. In either case, it needs to be fixed so that cohorts are always visible.

**Comment by openjck** [comment]
It looks like the latter: this cohort wasn't assigned a color. This will be an easy fix, I'll do it right now.

**Comment by rafrombrc** [comment]
Do cohorts need to be assigned colors manually? If so, will that be a problem when new experiments come down with never before seen cohorts?

**Comment by openjck** [comment]
At the moment, yeah. Manually assigning colors to cohorts allows us to keep those colors consistent. For example, *control* is always blue, *group A* is always yellow, etc.

If we know we'll get cohorts in the future with indeterminate names, we could look into another approach, like hashing the name of the cohort in a repeatable way to always get the same color. It comes with its own trade-offs and would take some work, but if we don't know the names of all cohorts coming through, it's better than having an invisible line.

**Comment by gregglind** [comment]
(re colors:  i would be perfectly satisfied with a 2-color, 3-color, 4-color solution, where 'control' or 'observe-only' is magic.  I claim it's [control, ...therest_sorted].  I think this is +1 to @openjck)
