### ISSUE TITLE
Also display "non-human-readable" metric name

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/experiments-viewer#301]
We should definitely put the human readable name front and center, but not showing the full name at all makes it much more difficult to find the right column if you want to take a closer look at a particular metric in re:dash or in a notebook

**Comment by sunahsuh** [comment]
No, I mean this: 
![screen shot 2017-10-26 at 2 05 32 pm](https://user-images.githubusercontent.com/953153/32072079-f6e36ff2-ba56-11e7-946a-b8d6e5f2e45a.png)

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.

Sunah, would you want this on Test Tube? If so I can open an issue in that repo.
