### ISSUE TITLE
[Test Tube API] Set "completed" property correctly

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#305]
The */experiments/* endpoint has a `completed` property which indicates whether the experiment has been completed. Right now, the value is always `true`, but @robhudson had the idea of setting it to `true` or `false` based on whether the experiment is continuing to receive pings.

See [this comment](https://github.com/mozilla/experiments-viewer/pull/300#discussion_r147783353) for more information.

**Comment by robhudson** [comment]
Copying here for simplicity...

> One idea... We will eventually stop receiving pings as the experiment wraps up. During import I can set all experiments as completed, then for those experiments where I do update the data, I set this flag to False b/c we are still receiving data.

**Comment by robhudson** [comment]
@sunahsuh Does the above sound like a decent idea?

**Comment by robhudson** [comment]
Related: https://github.com/mozilla/normandy/issues/804

**Comment by sunahsuh** [comment]
In my experience, we seem to continue to receive pings basically forever (try selecting a specific, disabled experiment and you'll see pings will trickle in for a while): https://sql.telemetry.mozilla.org/queries/6156#12426

On the pipeline end, we're *very* keen to stop processing experiments upon conclusion -- we've added a hack to do it but it's not a long-term solution.

**Comment by openjck** [comment]
Sorry to be a pain, but can we move discussion to the corresponding issue in Test Tube instead? API development will be happening there.

https://github.com/mozilla/firefox-test-tube/issues/24?
