### ISSUE TITLE
Cohorts should default to all on

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#31]
When switching from experiment A to experiment B, it looks like a) any cohort in exp B that matches a cohort name from exp A will retain the "on/off" state that was set in exp A, and b) any cohort in exp B that does *not* exist in exp A will default to "off". Ideally, when switching to a new experiment, all cohorts for that new experiment will always default to "on".

**Comment by spasovski** [comment]
https://github.com/mozilla/experiments-viewer/pull/41
