### ISSUE TITLE
Irrelevant cohorts show up in rollover text

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#32]
On stage, Exp 1 has a cohort named "group A" and Exp 2 has a cohort named "group B". If you start w Exp 1 and roll over the graphs, the text across the bottom bar shows you the values for "group A" and "control". If you switch to Exp 2, "group A" disappears and is replace by "group B", but "group A" *still* shows up in the rollover text across the bottom bar.

**Comment by openjck** [comment]
I think this was fixed on DV but not carried over for some reason.

**Comment by rafrombrc** [comment]
Hope so, bc that sounds like it would make for an easy fix. :)
