### ISSUE TITLE
Add ESC keyboard shortcut to close configuration modal

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#34]
Quoting @robhudson from [here](https://github.com/mozilla/experiments-viewer/commit/5744732a93e6f3aa9e7ffb31c1b592b9cf387c6c#commitcomment-21786675):

> Can we add ESC when the modal is open? With a lack of a button to close or apply the modal that was my default key to try. When that didn't work I finally figured out clicking anywhere closed the modal but it made me nervous. :)

**Comment by spasovski** [comment]
already done with last commit https://github.com/mozilla/experiments-viewer/commit/64e47ca
