### ISSUE TITLE
Cohort legend doesn't update w experiment change

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#40]
1. Hit staging site, see "Exp 1" selected w 'group A' and 'control' both displayed, and they're both showing up in the color legend.

2. Select "Exp 2" from drop-down, hit 'apply' button. 'group B' shows up in the cohort list, but the color legend doesn't update, it still shows 'group A' from before.

**Comment by spasovski** [comment]
https://github.com/mozilla/experiments-viewer/pull/41 fixed this by STR
