### ISSUE TITLE
Update metric types

### ISSUE THREAD

**Issue by robhudson** [mozilla/experiments-viewer#43]
I'm going to be changing the metric types to return the same thing I'm getting upstream. Which will change from `['categorical', 'numerical']` to a more descriptive set that looks like `['EnumeratedHistogram', 'FlagHistogram', 'CountHistogram', 'BooleanHistogram', 'ExponentialHistogram']`.

This will involve both front-end and back-end changes.

**Comment by robhudson** [comment]
Re-opening for the front-end side...

My suggestion would be to remove the conditionals between `categorical` and `numeric` and make all charts operate the same. A later step can be to customize charts on the new chart types if needed.

**Comment by rafrombrc** [comment]
Blocked by #37.

**Comment by spasovski** [comment]
https://github.com/mozilla/experiments-viewer/commit/160222c
