### ISSUE TITLE
Use a name other than "subgroup"

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#47]
We use the name *subgroup* on the front-end to refer to cohorts. But because we also want to use this platform elsewhere, where there may not be cohorts per se, we ideally want to use a word that would make sense for both. In other words, a term that means (cohort|population).

What would be a good name for this? Is population a generic term? @robhudson @spasovski

**Comment by robhudson** [comment]
I'm using population on the backend and it feels like a good general term.

**Comment by openjck** [comment]
Brendan wrote me a great, long email about terminology. Here's a quick highlight from it:

> If you are looking for one term that can capture the idea of the global-level population (e.g. "all telemetry clients") and also subpopulations ("clients on Beta", "experiment X, treatment Y"), I think "population" might be the most generic term.

Population it is!

**Comment by openjck** [comment]
This was fixed by https://github.com/openjck/experiments-viewer/commit/1952d11a7f0ece3a3429a24b43e5ce3fa5041970
