### ISSUE TITLE
Don't hardcode cohort colors

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#55]
We shouldn't hardcode a [cohort name] -> [cohort color] mapping in this project since we won't know the cohort names ahead of time.

For now, we can assign each cohort a random color except for *control*, which should always be the same color. Down the road, we can open an issue to make sure all cohorts have consistent colors (for example, *group A* would always be red and *group B* would always be blue) but to do that without knowing the names ahead of time we would have to have some kind of repeatable hash from name to color value. But that's outside the scope of this issue.

**Comment by rafrombrc** [comment]
Actually, @gregglind pointed out that a) if we always sort cohorts in the same order (see #54) and b) always assign colors in the same order, then the same cohorts will always be the same color for the same experiment. This seems pretty simple, I think we can pull that off right out of the gate, no?
