### ISSUE TITLE
Revisit chart detail page

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#63]
The chart detail page does not load when navigated to directly, for example by clicking [this link](https://moz-experiments-viewer-staging.herokuapp.com/chart/1/?sg=ALL&showOutliers=false).

When the chart detail page is navigated to from within the app (that is, by loading the homepage and then clicking on a chart), the detail page itself loads but the chart within it does not.

I think the former, at least, is due to the new default URL handling.

**Comment by rafrombrc** [comment]
We ended up removing the chart detail page so we weren't blocked on getting the full dashboard working. But now that experiments are running we've gotten feedback that the small charts can be hard to read. Reintroducing the chart detail page is one possible way to help folks drill down into better resolution.

**Comment by openjck** [comment]
Experiments Viewer has been replaced by Test Tube and now redirects to it.

We have a full-screen chart overview in Test Tube which serves the same purpose.
