### ISSUE TITLE
Add table for statistics data

### ISSUE THREAD

**Issue by robhudson** [mozilla/experiments-viewer#68]
Add a table at the same level as `api_point` to store statistics data coming from Sunah.

Suggested schema:
```
api_statistics
- id
- collection_id
- comparison_branch
- name
- p_value
- value
```

**Comment by gregglind** [comment]
Some Tigers and Dragons here, I think.

1.  claim: we are going to get this massively wrong in the first few revs.  Therefore, put a BIG API VERSION NUMBER on it.
2.  I have been through this with Sunah a few times.  I am have few nits here to suggest, I hope they seem helpful.


```
{
  groups:  ['control', 'b'],   // replaces both comparison_branch, is ordered?
  value:  2.8,
  test_name: '1-sided-z-score',
  pvalue:  '.01',
  ...
}

```

The model I have been using for this is how R does `test` objects.  They are all sadly different, but have some pieces in common.  

In any case, this will be live an learn for a while :)
