### ISSUE TITLE
Add subgroup to dataset API

### ISSUE THREAD

**Issue by robhudson** [mozilla/experiments-viewer#70]
Currently we have:
```
{
  "datasets": [
    {
      "id": 1,
      "name": "Experiment 1",
      "populations": ["control", "group A"]
    },
    ...
  ]
}
```

I propose we update to have a `subgroup` key with list of subgroups included:
```
{
  "datasets": [
    {
      "id": 1,
      "name": "Experiment 1",
      "populations": ["control", "group A"],
      "subgroups": ["Windows", "Mac", "Linux", "Other"]
    },
    ....
  ]
}
```

**Comment by robhudson** [comment]
@spasovski This is the suggested API to adding subgroups.

**Comment by openjck** [comment]
Will there be a name for the subgroup, for example *Operating Systems*?

**Comment by robhudson** [comment]
I don't have naming on the backend and neither does the parquet file.

**Comment by rafrombrc** [comment]
Hrm, that's a bit unfortunate. While it's not strictly required that the subgroups have a name,  I think we at least have to leave room for there to be more than one subgroup, which AFAICT isn't supported by this proposal. Maybe `subgroups` should be a nested JSON object?

**Comment by robhudson** [comment]
In the parquet file `subgroup` is a column. I expect it will eventually contain values like: 'Windows', 'Windows 7', 'Windows 10', 'Linux', 'Mac OS', 'Other'.

For the first iteration will that be enough and save the idea of nesting subgroups for a future feature if needed? Perhaps @sunahsuh can chime in here too.

**Comment by sunahsuh** [comment]
Makes sense, re: future subgroups, but is that something we can fake in the model/api layer for now? We can change the parquet format and import script later when we get to the point of actually having multiple groups.

**Comment by rafrombrc** [comment]
Sure, we can roll w the parquet format as is for now, but I still think we should structure the JSON that the API generates to support multiple subgroups so we won't have to make changes all the way through the stack.
